# Generated by Django 4.2.1 on 2023-05-17 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_genre_userprofile_genres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ('name',)},
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('goodreads_url', models.URLField(max_length=300)),
                ('img_url', models.URLField(max_length=300)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('ratings_count', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=255, null=True)),
                ('genres', models.ManyToManyField(blank=True, null=True, related_name='books', to='core.genre')),
            ],
        ),
    ]
