# Generated by Django 4.2.1 on 2023-05-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_avg_rating_book_avgrating_remove_book_genres_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
