# Generated by Django 4.2.1 on 2023-05-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('goodreads_url', models.URLField(max_length=300)),
                ('title', models.CharField(max_length=255)),
                ('titleComplete', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imgUrl', models.URLField(default='/media/cover.jpg', max_length=300)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=15, null=True)),
                ('isbn13', models.CharField(blank=True, max_length=255, null=True)),
                ('publisher', models.CharField(blank=True, max_length=255, null=True)),
                ('numPages', models.SmallIntegerField(blank=True, null=True)),
                ('publishYear', models.SmallIntegerField(blank=True, null=True)),
                ('avgRating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('soup', models.TextField(blank=True, null=True)),
                ('stemmedSoup', models.TextField(blank=True, null=True)),
                ('ratings_count', models.SmallIntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
