# Generated by Django 4.2.1 on 2023-05-19 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='avgRating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='imgUrl',
            field=models.URLField(blank=True, default='/media/cover.jpg', max_length=300, null=True),
        ),
    ]
