# Generated by Django 4.2.1 on 2023-05-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_book_avgrating_alter_book_imgurl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
