# Generated by Django 4.2.1 on 2023-05-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_book_options_remove_userprofile_genres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('book', models.ManyToManyField(to='core.book', verbose_name='books in genre')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
